### PR TITLE
Changed method for getting config data for Mercurial.

### PR DESCRIPTION
**Pull request by buzbohdan**
*config* command is not part of vanilla Mercurial, so usage of *hg config* causes error. Working with Mercurial config file was written by analogy to set_config method of HgRepository class. Also, renamed *key* variable to more canon *option*

### CODE REVIEW

**Comment by nijel** [comment]
Looks like it does not corectly handle unicode strings, see test failures.

**Comment by buzbohdan** [comment]
I forgot to remove print, will fix it tomorrow

**Comment by nijel** [comment]
Thanks, looks good now.

**Comment by buzbohdan** [comment]
And thank you for this great project!

**Pull request merged**
